import os

# config.py

TDENGINE_HOST = os.getenv("TDENGINE_HOST", "localhost")
TDENGINE_PORT = int(os.getenv("TDENGINE_PORT", "6030"))
TDENGINE_USER = os.getenv("TDENGINE_USER", "root")
TDENGINE_PASSWORD = os.getenv("TDENGINE_PASSWORD", "")
TDENGINE_DATABASE = os.getenv("TDENGINE_DATABASE", "cb_dev")

BAR_PERIOD = "5"
SOURCE = "akshare"

MAX_WORKERS = 4
RETRY_TIMES = 5
SLEEP_SECONDS = 2.0
USE_PROXY_FOR_MARKET_DATA = False
EASTMONEY_KLINE_LIMIT = 1000
MARKET_DATA_TIMEOUT = 20
MAX_CONSECUTIVE_FAILURES = 10
